
# Boite a jouet Cash Converter
# 155 x 105 x 33 (interieur) 

def addToyBox(sketch, _x, _y):
    HOLE_RADIUS = 1.55
    WIDTH = 155.0
    HEIGHT = 105.0
    HOLE_OFFSET = 5.0

    sketch.addRectangle(_x, _y, WIDTH, HEIGHT, 0)
    for hole_num, (a,b) in enumerate(((1.0, 1.0), (1.0, -1.0), (-1.0, -1.0), (-1.0, 1.0), )):
        x = a * (WIDTH / 2.0 - HOLE_OFFSET)  
        y = b * (HEIGHT / 2.0 - HOLE_OFFSET)  
        sketch.addCircle(x,y, HOLE_RADIUS)
    sketch.addCircle(_x, _y + HEIGHT / 2.0 - HOLE_OFFSET, HOLE_RADIUS)
    sketch.addCircle(_x, _y - HEIGHT / 2.0 + HOLE_OFFSET, HOLE_RADIUS)

